// app/layout.server.tsx

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  // Export a basic layout without the use client directive
  const ServerLayout = ({ children }: { children: React.ReactNode }) => {
    return (
      <>
        {children}
      </>
    );
  };
  
  export default ServerLayout;
  